# Use postgres/example user/password credentials
version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  db-data: