version: "3"

services:
  app: &app-config
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://username:passwd!@pg:5432/blog"
      CONFIG_NAME: ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      - "postgres"
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"


volumes:
  db-data: